In [3]:
#いろいろインポート
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from matplotlib import pyplot as plt
import seaborn
from pandas import DataFrame
from tqdm import tqdm
from imblearn.under_sampling import RandomUnderSampler #アンダーサンプリング用
import pickle
# 機械学習用
from sklearn.cluster import KMeans #クラスタリング用
from sklearn.ensemble import RandomForestClassifier#ランダムフォレスト
from copy import deepcopy as cp
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
import lightgbm as lgb
from sklearn.linear_model import LogisticRegression as LR

pd.set_option('display.width',400)#勝手に改行コードを入れられるのを防ぐ
place='suminoe'

In [4]:
#モデルスコアデータの読み込み
#score_df = pd.read_csv('../csv/model_score_date_{}.csv'.format(place))#dateアリのモデル
score_df = pd.read_csv('../csv/{}_model_score_normal.csv'.format(place))#dateなしのモデル
score_df=score_df.drop(["Unnamed: 0"],axis=1)#csvファイルについている名無しの列を削除
display(score_df)

       target_com  depth  target_per       総収益      投資金額    出現数   購買予測数        利益率     購買的中率    的中数
0             1.0    4.0        51.0  354000.0  406900.0  331.0  4069.0  86.999263  8.134677  331.0
1             1.0    4.0        52.0  354000.0  406900.0  331.0  4069.0  86.999263  8.134677  331.0
2             1.0    4.0        53.0  354000.0  406900.0  331.0  4069.0  86.999263  8.134677  331.0
3             1.0    4.0        54.0  354000.0  406900.0  331.0  4069.0  86.999263  8.134677  331.0
4             1.0    4.0        55.0  354000.0  406900.0  331.0  4069.0  86.999263  8.134677  331.0
...           ...    ...         ...       ...       ...    ...     ...        ...       ...    ...
13855        28.0    8.0       145.0   18580.0   25900.0   19.0   259.0  71.737452  2.702703    7.0
13856        28.0    8.0       146.0   17530.0   22000.0   19.0   220.0  79.681818  2.727273    6.0
13857        28.0    8.0       147.0   18580.0   21000.0   19.0   210.0  88.476190  3.333333    7.0
13858        28.0    8.0       148.0   18580.0   23300.0   19.0   233.0  79.742489  3.004292    7.0
13859        28.0    8.0       149.0   10890.0   20900.0   19.0   209.0  52.105263  2.870813    6.0

[13860 rows x 10 columns]

#### モデル性能評価用のデータフレーム作成(result_comごとの閾値を持つ)

In [5]:
#学習データの読み込み
result_df = pd.read_csv('../csv/train_{}_date.csv'.format(place))
result_df=result_df.drop(["Unnamed: 0"],axis=1)#csvファイルについている名無しの列を削除


df=result_df.copy()

#学習、テストデータ切り分け(dateを使って学習データを切り分ける。)

df['date']=pd.to_datetime(df['date'])#文字列なのでdateを日付型に変換
df['year']=df['date'].dt.year
valid_df = df[(df['year']==2019) | ((df['year']==2020) )]#2019,2020のデータを検証用データに。
train_df =  df[(df['year']!=2019) & ((df['year']!=2020) )]#そのほかを学習データに
#学習データを切り分けたらdateとyearはいらないから削除する
valid_df=valid_df.drop(['year'],axis=1)
train_df=train_df.drop(['year'],axis=1)
valid_df=valid_df.drop(['date'],axis=1)
train_df=train_df.drop(['date'],axis=1)

train_money=pd.Series(train_df['money'])
valid_money=pd.Series(valid_df['money'])

#出現数の分布
result_com_s=valid_df['result_com'].value_counts()
result_com_s=result_com_s.sort_index()
gain_mean=valid_df.groupby('result_com')['money'].mean()
gain_mean=gain_mean.sort_index()

gain_median=valid_df.groupby('result_com')['money'].median()
gain_median=gain_median.sort_index()
result_com_df=pd.DataFrame({'result_com':result_com_s.index,
                            'result_com_num':result_com_s.values,
                            'result_com_per':result_com_s.values/sum(result_com_s.values)*100,
                            'gain_mean':gain_mean.values,
                            'gain_median':gain_median.values,})
display(result_com_df)

     result_com  result_com_num  result_com_per     gain_mean  gain_median
0             1             331        8.134677   1069.486405        820.0
1             2             250        6.144016   1457.920000        965.0
2             3             154        3.784714   2160.064935       1270.0
3             4             130        3.194888   2351.000000       1580.0
4             5             278        6.832145   1386.294964       1080.0
..          ...             ...             ...           ...          ...
114         116               2        0.049152  19980.000000      19980.0
115         117               3        0.073728  14260.000000       9200.0
116         118               4        0.098304  14757.500000      10905.0
117         119               4        0.098304  14870.000000      14645.0
118         120               2        0.049152  14265.000000      14265.0

[119 rows x 5 columns]

### モデル性能評価機能

In [6]:
#基準をクリアしたモデルを格納するdf
depths_arr=[4,5,6,7,8]
model_para_df=pd.DataFrame(columns=['target_com','depth','target_per','総収益', '投資金額','出現数','購買予測数','利益率','購買的中率','的中数'])
for target_com in result_com_df['result_com'].values:
    target_com_df=score_df[score_df['target_com']==target_com]
    #閾値の作成===============================================================
    gain_th=110#利益率の閾値
    result_s=result_com_df[result_com_df['result_com']==target_com]
    buy_accuracy_th=result_s['result_com_per'].values[0]*1.1#買ったうちの的中率の閾値
    num_tp_th=result_s['result_com_num'].values[0]*0.2#あたった回数の閾値(出現回数の20%が的中)
    
    diff_gain_th=108#利益率の閾値
    diff_buy_accuracy_th=result_s['result_com_per'].values[0]*1.1#前後モデルの買ったうちの的中率の閾値
    diff_num_tp_th=result_s['result_com_num'].values[0]*0.13#前後モデルのあたった回数の閾値(出現回数の20%が的中)
    
    #==========================================================
    for target_depth in depths_arr:
        target_com_depth_df=target_com_df[target_com_df['depth']==target_depth]
        
        len_df=len(target_com_depth_df)
        df=target_com_depth_df.copy()
        df['number_i']=np.arange(0,len_df,1)
        
        for _, row in df.iterrows():
            if ((row['number_i']==0) or (row['number_i']==1) or (row['number_i']==len_df-2) or (row['number_i']==len_df-1)):
                pass
            else:
                #前後のモデルのスコア===================================
                diff_m2_row=df[df['number_i']==(row['number_i']-2)]
                diff_m1_row=df[df['number_i']==(row['number_i']-1)]
                diff_p1_row=df[df['number_i']==(row['number_i']+1)]
                diff_p2_row=df[df['number_i']==(row['number_i']+2)]
                diff_models=[diff_m2_row,diff_m1_row,diff_p1_row,diff_p2_row]
                #===================================================
                if ((row['利益率']>gain_th) and (row['購買的中率']>buy_accuracy_th) and (row['的中数']>=num_tp_th)):#初めに真ん中のモデルの性能評価
                    #前後モデルの評価
                    flag_arr=[0,0,0,0]
                    for index in range(len(flag_arr)):

                        diff_model=diff_models[index].iloc[0,:]
                        if ((diff_model['利益率']>diff_gain_th) and (diff_model['購買的中率']>diff_buy_accuracy_th) and (diff_model['的中数']>=diff_num_tp_th)):#前後モデルの性能評価
                            flag_arr[index]=1
                        else:
                            pass
                    if sum(flag_arr)==4:
                        model_para_df=model_para_df.append(row)
                        
                else:
                    pass

In [7]:
model_para_df

       target_com  depth  target_per       総収益      投資金額    出現数   購買予測数         利益率      購買的中率    的中数  number_i
2038          5.0    4.0       109.0   86560.0   71500.0  278.0   715.0  121.062937  11.328671   81.0      58.0
2039          5.0    4.0       110.0   66330.0   56900.0  278.0   569.0  116.572935  10.544815   60.0      59.0
2140          5.0    5.0       112.0   73600.0   57000.0  278.0   570.0  129.122807  12.105263   69.0      61.0
2237          5.0    6.0       110.0  114010.0   96400.0  278.0   964.0  118.267635  10.788382  104.0      59.0
2238          5.0    6.0       111.0  106270.0   89600.0  278.0   896.0  118.604911  10.825893   97.0      60.0
...           ...    ...         ...       ...       ...    ...     ...         ...        ...    ...       ...
13293        27.0    8.0        78.0  247780.0  197200.0   29.0  1972.0  125.649087   1.115619   22.0      27.0
13294        27.0    8.0        79.0  213850.0  179600.0   29.0  1796.0  119.070156   1.169265   21.0      28.0
13295        27.0    8.0        80.0  213850.0  172400.0   29.0  1724.0  124.042923   1.218097   21.0      29.0
13296        27.0    8.0        81.0  213850.0  172400.0   29.0  1724.0  124.042923   1.218097   21.0      30.0
13297        27.0    8.0        82.0  213850.0  171400.0   29.0  1714.0  124.766628   1.225204   21.0      31.0

[116 rows x 11 columns]

In [8]:
#model_para_df.to_csv('../csv/{}_good_score_model_date.csv'.format(place), encoding='utf_8_sig')
model_para_df.to_csv('../csv/{}_good_score_model_normal.csv'.format(place), encoding='utf_8_sig')

In [9]:
diff_model

target_com       27.000000
depth             8.000000
target_per      140.000000
総収益           12260.000000
投資金額          30200.000000
出現数              29.000000
購買予測数           302.000000
利益率              40.596026
購買的中率             1.655629
的中数               5.000000
number_i         89.000000
Name: 13355, dtype: float64

In [10]:
len_df

0

In [11]:
type(diff_model)

pandas.core.series.Series